version: '3'
services:
  postgres:
    container_name: postgresTravelTips
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 'workdb123'
      POSTGRES_USER: 'adminTravelTips'
      POSTGRES_DB: 'travelTips'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: {}
