version: '3'
services:
  postgres:
    container_name: postgresv2b
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 'v2bPassword'
      POSTGRES_USER: 'adminv2b'
      POSTGRES_DB: 'v2b'
    ports:
      - '5650:5432'
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: {}
